How severe weather events can cause public health and economic problems
=======================================================================

Synopsis - Summary 
-----------------------------------------------------------------------
 Storms and severe weather can have big health and economic consequences. The understanding of the specific types of events associated with the greatest consequences can help inform disaster preparedness policies that can potentially mitigate damages and help target limited resources. 
 The purpose of the current study is to identify the specific weather-related events that are associated witht the greatest amount of economic and health consequence. 
 Data for this analysis come from the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database. Based on an exploratory analysis of the NOAA storm database, the storm related events associated with the greatest number of fatalities were tornados and heat. The greatest amount of economic damage was due to winds (e.g., tropical storm, storm surge, hurricane, and typhoons) and flooding.



Phase 1 - Data Processing
-----------------------------------------------------------------------

```{r echo = FALSE}
Init <- function(workDirStr="C:/Users/hsofoian/Desktop/DataScience/Course 5 - Reproducible Research/RepData_PeerAssessment2"){
        setwd(workDirStr)      
}
Init()
```

# Read Data
```{r echo = TRUE}
rawdata <- read.csv(bzfile("C:/Users/hsofoian/Desktop/DataScience/Course 5 - Reproducible Research/data/repdata_data_StormData.csv.bz2"))

```

# Relevant fields + Homogenous
```{r}
data <- rawdata[,c("STATE","EVTYPE","FATALITIES","INJURIES","PROPDMG","PROPDMGEXP","CROPDMG","CROPDMGEXP")]
colnames(data) <- tolower(colnames(data)) 

data$evtype <- factor(toupper(data$evtype)) 
data$propdmgexp <- factor(toupper(data$propdmgexp))
data$cropdmgexp <- factor(toupper(data$cropdmgexp))
```

# Convert the values of the columns **propdmg**
```{r}
exponents <- data.frame(c("","0","H","K","M","B"),c(1,1,10^2,10^3,10^6,10^9))
colnames(exponents) <- c("validexp","multiplier")

data <- subset(data, (cropdmgexp %in% exponents$validexp) & (propdmgexp %in% exponents$validexp))

#convert damage values in number
colnames(exponents) <- c("validexp","propdmgmultiplier")
data <- merge(data, exponents, by.x="propdmgexp", by.y="validexp")
data$propdmg <- (data$propdmg*data$propdmgmultiplier)

colnames(exponents) <- c("validexp","cropdmgmultiplier")
data <- merge(data, exponents, by.x="cropdmgexp", by.y="validexp")
data$cropdmg <- (data$cropdmg*data$cropdmgmultiplier)
```

A - Calculation of economic impact
--------------------------------

Calculation of the **economic impact** of different weather events. 
```{r}
data$totalCost <- data$propdmg+data$cropdmg #define total cost
economicData <- subset(data, totalCost > 0) #select only events with cost > 0

economicData <- economicData[,c("state","evtype","totalCost")]

library(reshape2)
library(plyr)
economicData <- dcast(economicData, state~evtype,fun.aggregate=sum,value.var="totalCost")
economicData <- melt(economicData, id="state")
economicData <- arrange(economicData, state, desc(value))
```

The event that generated the higher **totalCost**:
```{r}
economicData <- split(economicData,economicData$state)
economicData <- lapply(economicData, function(x) x[1,])
economicData <- melt(economicData, id="state", id.vars="variable", measure.vars="value")
```


B - Calculation of health impact
------------------------------

Calculation of the **health impact** of fatalities and injuries caused by each event. 
```{r}
#define total health cost through pca
pca <- data[,c("fatalities","injuries")]
pca <- princomp(pca)
summary(pca)

data$totalHealthCost <- pca$scores[,1]
healthData <- subset(data, totalHealthCost > 0) #select only events with cost > 0
healthData <- healthData[,c("state","evtype","totalHealthCost")]
```

```{r}
#sum over states by type of event and arrange for decreasing costs
healthData <- dcast(healthData, state~evtype,fun.aggregate=sum,value.var="totalHealthCost")
healthData <- melt(healthData, id="state")
healthData <- arrange(healthData, state, desc(value))
healthData <- split(healthData,healthData$state)
healthData <- lapply(healthData, function(x) x[1,])
healthData <- melt(healthData, id="state", id.vars="variable", measure.vars="value")
```


Phase 2 - Results
-----------------------------------------------------------------------

Economic impact
------------------------------

Costs in Bn $
```{r}
colnames(economicData) <- c("eventType","totalCost_Bn","state")
economicData <- economicData[,c("state","eventType","totalCost_Bn")]

# convert in Bn$
economicData$totalCost_Bn <- economicData$totalCost_Bn/10^9
economicData[!is.na(economicData$totalCost_Bn),]
```

```{r}
library(maps)

economicData <- economicData[!is.na(economicData$totalCost_Bn),]

data(state.fips)
tmp <- state.fips
tmp <- data.frame(tmp$abb,tmp$polyname)
colnames(tmp) <- c("state","stateName")
economicData <- merge(economicData,tmp)

economicData$totalCost_Bn <- (economicData$totalCost_Bn)^(1/3)

economicData$normCost <- (economicData$totalCost_Bn-min(economicData$totalCost_Bn))/(max(economicData$totalCost_Bn)-min(economicData$totalCost_Bn))

#plot
pal <- colorRamp(c("white","black"))
map("state", regions = economicData$stateName, lty = 1, lwd =1, boundary=TRUE, fill=TRUE, col=rgb(pal(economicData$normCost)/255))
title(main="Most harmed states by weather events with economic impact\n (white: least harmed, black: most harmed)")
```

Health impact
-------------------------

```{r}
colnames(healthData) <- c("eventType","totalHealthCost","state")
healthData <- healthData[,c("state","eventType","totalHealthCost")]
healthData[!is.na(healthData$totalHealthCost),]
```

```{r}
library(maps)

healthData <- healthData[!is.na(healthData$totalHealthCost),]

data(state.fips)
tmp <- state.fips
tmp <- data.frame(tmp$abb,tmp$polyname)
colnames(tmp) <- c("state","stateName")
healthData <- merge(healthData,tmp)

healthData$normCost <- (healthData$totalHealthCost-min(healthData$totalHealthCost))/(max(healthData$totalHealthCost)-min(healthData$totalHealthCost))

#plot
pal <- colorRamp(c("white","blue"))
map("state", regions = healthData$stateName, lty = 1, lwd =1, boundary=TRUE, fill=TRUE, col=rgb(pal(healthData$normCost)/255))
title(main="Most harmed states by weather events with health impact\n (blue: most harmed, white: least harmed)")
```
